server:
  port: 8080


spring:

  application:
    name: API-Simulador

  datasource:
    sqlserver:
      jdbc-url: jdbc:sqlserver://dbhackathon.database.windows.net:1433;database=hack
      username: hack
      password: Password23
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    h2:
      jdbc-url: jdbc:h2:mem:simulador;DB_CLOSE_DELAY=-1;
      username: sa
      password:
      driver-class-name: org.h2.Driver

    cache:
      type: caffeine
      cache-names: obterProdutos
      caffeine.spec: maximumSize=100,expireAfterWrite=1m


  kafka:
    bootstrap-servers: eventhack.servicebus.windows.net:9093
    properties:
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://eventhack.servicebus.windows.net/;SharedAccessKeyName=hack;SharedAccessKey=HeHeVaVqyVkntO2FnjQcs2Ilh/4MUDo4y+AEhKp8z+g=";
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  h2:
    console:
      enabled: true
topic:
  name: simulacoes

springdoc:
  api-docs:
    version: "openapi_3_0"

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.cache: trace

